
import java.awt.*;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author andreskis
 */
public class SorryMenu extends javax.swing.JFrame
{
   Container contentpane = new Container();
   protected int numPlyrs;
   private final int PLYR2 = 2;
   private final int PLYR3 = 3;
   private final int PLYR4 = 4;
   private final int MAX_NAME_LN = 16;
   public PlayerList list;
   /**
    * Initializes  Sorry
    */
   /**
    * Creates new form playerName
    */
   private void setVisibility()
   {
      if( numPlyrs == PLYR2)
      {
         plyr3Name.setVisible(false);
         plyr4Name.setVisible(false);
         list = new PlayerList(numPlyrs);
      }
      
      else if( numPlyrs == PLYR3)
      {
         plyr3Name.setVisible(true);
         plyr4Name.setVisible(false);
         list = new PlayerList(numPlyrs);
      }
      else
      {
         plyr3Name.setVisible(true);
         plyr4Name.setVisible(true);
         list = new PlayerList(numPlyrs);
      }
   }

   /**
    * Creates new form SorryMenu
    */
   public SorryMenu()
   {
      initComponents();       
      shownum();
   }


   /**
    * This method is called from within the constructor to initialize the
    * form. WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpane = new javax.swing.JLayeredPane();
        pnum = new javax.swing.JPanel();
        numPlayerBox = new javax.swing.JComboBox();
        title = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        namPan = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        plyr1Name = new javax.swing.JTextField();
        plyr2Name = new javax.swing.JTextField();
        plyr3Name = new javax.swing.JTextField();
        plyr4Name = new javax.swing.JTextField();
        playButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        quitButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(510, 330));
        setName("menu"); // NOI18N
        setPreferredSize(jpane.getSize());
        setResizable(false);

        jpane.setMinimumSize(new java.awt.Dimension(508, 328));

        pnum.setBackground(new java.awt.Color(0, 204, 204));
        pnum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnum.setLayout(null);

        numPlayerBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numPlayerBox.setMaximumRowCount(3);
        numPlayerBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2 Players", "3 Players", "4 Players" }));
        numPlayerBox.setToolTipText("Select Number of Players"); // NOI18N
        numPlayerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPlayerBoxActionPerformed(evt);
            }
        });
        pnum.add(numPlayerBox);
        numPlayerBox.setBounds(160, 120, 160, 30);

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setText("Select Number of Players:");
        pnum.add(title);
        title.setBounds(10, 10, 471, 40);

        nextButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        pnum.add(nextButton);
        nextButton.setBounds(390, 260, 90, 30);

        quitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        pnum.add(quitButton);
        quitButton.setBounds(10, 260, 80, 30);

        jpane.add(pnum);
        pnum.setBounds(0, 0, 510, 330);

        namPan.setBackground(new java.awt.Color(0, 204, 255));
        namPan.setMinimumSize(new java.awt.Dimension(510, 330));
        namPan.setPreferredSize(new java.awt.Dimension(510, 330));
        namPan.setLayout(null);

        title1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title1.setText("Enter Player Names:");
        namPan.add(title1);
        title1.setBounds(30, 10, 371, 40);

        plyr1Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        plyr1Name.setText("Enter Player 1's Name");
        plyr1Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        plyr1Name.setName(""); // NOI18N
        plyr1Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plyr1NameMouseClicked(evt);
            }
        });
        namPan.add(plyr1Name);
        plyr1Name.setBounds(100, 60, 250, 40);

        plyr2Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        plyr2Name.setText("Enter Player 2's Name");
        plyr2Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        plyr2Name.setSelectionStart(0);
        plyr2Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plyr2NameMouseClicked(evt);
            }
        });
        namPan.add(plyr2Name);
        plyr2Name.setBounds(100, 110, 250, 40);

        plyr3Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        plyr3Name.setText("Enter Player 3's Name");
        plyr3Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 3));
        plyr3Name.setSelectionStart(0);
        plyr3Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plyr3NameMouseClicked(evt);
            }
        });
        namPan.add(plyr3Name);
        plyr3Name.setBounds(100, 160, 250, 40);

        plyr4Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        plyr4Name.setText("Enter Player 4's Name");
        plyr4Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 3));
        plyr4Name.setSelectionStart(0);
        plyr4Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plyr4NameMouseClicked(evt);
            }
        });
        namPan.add(plyr4Name);
        plyr4Name.setBounds(100, 210, 250, 40);

        playButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playButton.setText("Play!");
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playButtonMouseEntered(evt);
            }
        });
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        namPan.add(playButton);
        playButton.setBounds(360, 260, 90, 40);

        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        namPan.add(backButton);
        backButton.setBounds(190, 260, 90, 40);

        quitButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        quitButton1.setText("Quit");
        quitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButton1ActionPerformed(evt);
            }
        });
        namPan.add(quitButton1);
        quitButton1.setBounds(20, 260, 90, 40);

        jpane.add(namPan);
        namPan.setBounds(0, 0, 510, 330);

        getContentPane().add(jpane, java.awt.BorderLayout.CENTER);
        jpane.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleParent(jpane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void numPlayerBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numPlayerBoxActionPerformed
   {//GEN-HEADEREND:event_numPlayerBoxActionPerformed

   }//GEN-LAST:event_numPlayerBoxActionPerformed

   private void nextButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nextButtonActionPerformed
   {//GEN-HEADEREND:event_nextButtonActionPerformed
      numPlyrs = numPlayerBox.getSelectedIndex() + 2;
      showpname();

   }//GEN-LAST:event_nextButtonActionPerformed

   private void quitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitButtonActionPerformed
   {//GEN-HEADEREND:event_quitButtonActionPerformed
      System.exit(0);
   }//GEN-LAST:event_quitButtonActionPerformed

   private void playButtonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_playButtonMouseEntered
   {//GEN-HEADEREND:event_playButtonMouseEntered
      //change color for fun
   }//GEN-LAST:event_playButtonMouseEntered

   private void playButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_playButtonActionPerformed
   {//GEN-HEADEREND:event_playButtonActionPerformed
      boolean err1, err2, err3 = false, err4 = false;
      err1 = getPlyr1Name();
      err2 = getPlyr2Name();
      
      if( numPlyrs >= PLYR3 )
        err3 = getPlyr3Name();
      
      if( numPlyrs == PLYR4 )
        err4 = getPlyr4Name();
      
      if( err1 )
         JOptionPane.showMessageDialog(jpane, "Error: enter a name for "
                       + "player 1 that is no more than 16 characters long.");
      if( err2 )
         JOptionPane.showMessageDialog(jpane, "Error: enter a name for "
                       + "player 2 that is no more than 16 characters long.");
      if( err3 )
         JOptionPane.showMessageDialog(jpane, "Error: enter a name for "
                       + "player 3 that is no more than 16 characters long.");
      if( err4 )
         JOptionPane.showMessageDialog(jpane, "Error: enter a name for "
                       + "player 4 that is no more than 16 characters long.");
      if( !err1 && !err2 && !err3 && !err4 )
      {
        setVisible(false);
        SorryBoard sb = new SorryBoard(list);
        sb.setVisible(true);
        
      }
   }//GEN-LAST:event_playButtonActionPerformed

   private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
   {//GEN-HEADEREND:event_backButtonActionPerformed
      shownum();      // go to numPlayers screen
   }//GEN-LAST:event_backButtonActionPerformed

   private void quitButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitButton1ActionPerformed
   {//GEN-HEADEREND:event_quitButton1ActionPerformed
      System.exit(0);
   }//GEN-LAST:event_quitButton1ActionPerformed

    private void plyr1NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plyr1NameMouseClicked
      if( plyr1Name.getText().equals("Enter Player 1's Name") )
         plyr1Name.setText("");
    }//GEN-LAST:event_plyr1NameMouseClicked

    private void plyr2NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plyr2NameMouseClicked
      if( plyr2Name.getText().equals("Enter Player 2's Name") )
         plyr2Name.setText("");
    }//GEN-LAST:event_plyr2NameMouseClicked

    private void plyr3NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plyr3NameMouseClicked
       if( plyr3Name.getText().equals("Enter Player 3's Name") )
         plyr3Name.setText("");
    }//GEN-LAST:event_plyr3NameMouseClicked

    private void plyr4NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plyr4NameMouseClicked
      if( plyr4Name.getText().equals("Enter Player 4's Name") )
         plyr4Name.setText("");
    }//GEN-LAST:event_plyr4NameMouseClicked

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(SorryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(SorryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(SorryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(SorryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new SorryMenu().setVisible(true);
            
         }
      });
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLayeredPane jpane;
    private javax.swing.JPanel namPan;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox numPlayerBox;
    private javax.swing.JButton playButton;
    private javax.swing.JTextField plyr1Name;
    private javax.swing.JTextField plyr2Name;
    private javax.swing.JTextField plyr3Name;
    private javax.swing.JTextField plyr4Name;
    private javax.swing.JPanel pnum;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton quitButton1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables

   protected void shownum()
   {   
      namPan.setVisible(false);
      pnum.setVisible(true); 
      jpane.moveToFront(pnum);
      pnum.requestFocus();
      
   }
   protected void showpname()
   {    
      pnum.setVisible(false);
      namPan.setVisible(true);
      jpane.moveToFront(namPan);
      setVisibility();
      namPan.requestFocus();  
   }
   
 private boolean getPlyr1Name()
   { 
      String name = plyr1Name.getText();
      if( !name.equals("Enter Player 1's Name") 
          && name.length() <= MAX_NAME_LN && !name.equals("") )
      {
         list.add(new Player(name, 1));
         return false;
      }
      return true;
   }
    
   private boolean getPlyr2Name()
   {
      String name = plyr2Name.getText();
      if( !name.equals("Enter Player 2's Name") 
          && name.length() <= MAX_NAME_LN && !name.equals("") )
      {
         list.add(new Player(name, PLYR2));
         return false;
      }
      return true;

   }
    
   private boolean getPlyr3Name()
   {
      String name = plyr3Name.getText();
      if( !name.equals("Enter Player 3's Name") 
          && name.length() <= MAX_NAME_LN && !name.equals("") )
      {
         list.add(new Player(name, PLYR3));
         return false;
      }
      return true;
   }
   
   private boolean getPlyr4Name()
   {
      String name = plyr4Name.getText();
      if( !name.equals("Enter Player 4's Name") 
          && name.length() <= MAX_NAME_LN && !name.equals("") )
      {
         list.add(new Player(name, PLYR4));
         return false;
      }
      return true;
    }
}


