/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sicko
 */
public class EditClass extends javax.swing.JFrame {

    /**
     * Creates new form AddClass
     */
    public EditClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Existing Class");
        getContentPane().setLayout(null);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 27, 14);

        jLabel2.setText("Start Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 60, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("End Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 50, 14);

        jLabel4.setText("Start Time");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 60, 14);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("End Time");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 50, 14);

        jLabel6.setText("Meeting Days");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 170, 70, 14);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Monday");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(90, 150, 63, 23);

        jCheckBox2.setText("Tuesday");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(170, 150, 67, 23);

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Wednesday");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(250, 150, 90, 23);

        jCheckBox4.setText("Thursday");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(90, 180, 81, 23);

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Friday");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(170, 180, 55, 23);

        jCheckBox6.setText("Saturday");
        getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(250, 180, 69, 23);

        jCheckBox7.setText("Sunday");
        getContentPane().add(jCheckBox7);
        jCheckBox7.setBounds(330, 180, 70, 23);

        jLabel7.setText("Area");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 220, 23, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aerobics Center" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(50, 220, 110, 20);

        jTextField1.setText("Aerobics");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 10, 80, 20);

        jTextField5.setText("20");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(120, 40, 20, 20);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("/");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 40, 10, 20);

        jTextField6.setText("07");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(90, 40, 20, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("/");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 40, 10, 20);

        jTextField7.setText("2015");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(150, 40, 40, 20);

        jTextField8.setText("21");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(120, 70, 20, 20);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("/");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 70, 10, 20);

        jTextField9.setText("08");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(90, 70, 20, 20);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("/");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 70, 10, 20);

        jTextField10.setText("2015");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(150, 70, 40, 20);

        jTextField2.setText("17");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(90, 100, 20, 20);

        jTextField3.setText("00");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(120, 100, 20, 20);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(":");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(110, 100, 10, 20);

        jTextField4.setText("19");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(90, 130, 20, 20);

        jTextField11.setText("00");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(120, 130, 20, 20);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(":");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(110, 130, 10, 20);

        jButton1.setText("SAVE");
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 270, 57, 23);

        jButton2.setText("CANCEL");
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 270, 71, 23);

        jButton3.setText("BACK");
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 270, 59, 23);

        jButton4.setText("Add New Area");
        jButton4.setToolTipText("");
        getContentPane().add(jButton4);
        jButton4.setBounds(170, 220, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
