/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lab03;

/**
 *
 * @author muleskib
 */
public class My_Lab3_Frame extends java.awt.Frame
{

   /**
    * Creates new form My_Lab3_Frame
    */
   public My_Lab3_Frame()
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the
    * form. WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listOfWords = new java.awt.List();
        addButton = new java.awt.Button();
        removeButton = new java.awt.Button();
        label1 = new java.awt.Label();
        wordField = new java.awt.TextField();

        setMaximumSize(new java.awt.Dimension(500, 500));
        setTitle("My Lab3 Frame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        listOfWords.setName("listOfWords"); // NOI18N
        add(listOfWords);
        listOfWords.setBounds(50, 50, 90, 140);

        addButton.setLabel("Add word");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton);
        addButton.setBounds(160, 50, 67, 24);

        removeButton.setLabel("Remove Selected Word");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        add(removeButton);
        removeButton.setBounds(170, 140, 140, 24);

        label1.setText("Word to Add:");
        add(label1);
        label1.setBounds(170, 100, 70, 20);
        add(wordField);
        wordField.setBounds(250, 100, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
    * Exit the Application
    */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       System.exit(0);
    }//GEN-LAST:event_exitForm

   private void addButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addButtonActionPerformed
   {//GEN-HEADEREND:event_addButtonActionPerformed
      String text;
      if(!wordField.getText().equalsIgnoreCase(""))
      {
         text = wordField.getText();
         listOfWords.add(text);
      }
      else
         System.out.println("Void textbox");
   }//GEN-LAST:event_addButtonActionPerformed

   private void removeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_removeButtonActionPerformed
   {//GEN-HEADEREND:event_removeButtonActionPerformed
      int index;
      if(listOfWords.getSelectedIndex() != -1)
      {
         index = listOfWords.getSelectedIndex();
         listOfWords.remove(index);
      }
      else
         System.out.println("Void list");
   }//GEN-LAST:event_removeButtonActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new My_Lab3_Frame().setVisible(true);
         }
      });
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addButton;
    private java.awt.Label label1;
    private java.awt.List listOfWords;
    private java.awt.Button removeButton;
    private java.awt.TextField wordField;
    // End of variables declaration//GEN-END:variables
}
